version: '3.8'

services:

  postgres:
    image: postgres:16
    container_name: perfin-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    image: ghcr.io/navise/perfin-backend:latest
    container_name: perfin-backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  frontend:
    image: ghcr.io/navise/perfin-frontend:latest
    container_name: perfin-frontend
    restart: always
    env_file:
      - .env
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata:
