name: Build & Push to GHCR

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
      VITE_DATADOG_APPLICATION_ID: ${{ secrets.VITE_DATADOG_APPLICATION_ID }}
      VITE_DATADOG_CLIENT_TOKEN: ${{ secrets.VITE_DATADOG_CLIENT_TOKEN }}
      VITE_DATADOG_SITE: ${{ secrets.VITE_DATADOG_SITE }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push backend image
        run: |
          docker build -t ghcr.io/navise/perfin-backend:latest ./backend
          docker push ghcr.io/navise/perfin-backend:latest

      - name: Build and push frontend image with VITE_ args
        run: |
          docker build \
            --build-arg VITE_API_BASE_URL=$VITE_API_BASE_URL \
            --build-arg VITE_DATADOG_APPLICATION_ID=$VITE_DATADOG_APPLICATION_ID \
            --build-arg VITE_DATADOG_CLIENT_TOKEN=$VITE_DATADOG_CLIENT_TOKEN \
            --build-arg VITE_DATADOG_SITE=$VITE_DATADOG_SITE \
            -t ghcr.io/navise/perfin-frontend:latest \
            ./frontend
          docker push ghcr.io/navise/perfin-frontend:latest
